### ISSUE TITLE
Representing Multiple Email Addresses

### ISSUE THREAD

**Issue by dillonredding** [dillonredding/siren-extensions#2]
So, we've defined the [`multiple`][1] extension for `"email"` fields, which adds type semantics around the field's `value` property. In particular:

> When `multiple` is `true` and `type` is `email`, the field's `value` MUST be an array of strings.

However, as I'm implementing field validation in [Siren.js][2], I'm starting to wonder if that's "correct". Specifically, I stumbled across the [value sanitization algorithm][3] for a [multiple-email `input`][4]:

> 1. [Split on commas](https://infra.spec.whatwg.org/#split-on-commas) the element's [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value), [strip leading and trailing ASCII whitespace](https://infra.spec.whatwg.org/#strip-leading-and-trailing-ascii-whitespace) from each resulting token, if any, and let the element's [values](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-values) be the (possibly empty) resulting list of (possibly empty) tokens, maintaining the original order.
> 2. Let the element's [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value) be the result of concatenating the element's [values](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-values), separating each value from the next by a single U+002C COMMA character (,), maintaining the list's order.

To give a little more context, an input's value sanitization algorithm runs when [setting an input's `value`][5] in HTML. This is not currently a thing in Siren.js, but we *may* implement it in the future. Regardless, the point is that an `input`'s `value` is never an array, it's just a CSV of emails. Also, the client ultimately sends multiple email addresses as `email1,email2,...,emailN`.

All that said, I think we need to update the type requirement for `value`. I see two possible resolutions for this, but I'm open to others:

1. "...`value` MUST be a string containing a list of comma-separated email addresses."
1. "...`value` MUST be either an array of strings or a string of comma-separated email addresses."

Allowing arrays would be fine for Siren.js since an array value will be converted to a string, which results in a CSV anyway:

```js
String(['foo@bar.com', 'bar@baz.org'])
// => 'foo@bar.com,bar@baz.org'
```

However, I'm not sure if other languages/implementations would handle this so gracefully.

[1]: https://github.com/dillonredding/siren-extensions#multiple
[2]: https://github.com/dillonredding/sirenjs/tree/0.1.0
[3]: https://html.spec.whatwg.org/multipage/input.html#value-sanitization-algorithm
[4]: https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)
[5]: https://html.spec.whatwg.org/multipage/input.html#dom-input-value-value

**Comment by raworre** [comment]
Given that the sanitization algorithm for HTML already treats this as a comma delimited list of email addresses, and the client will ultimately send a list in a comma delimited string I think that this should be updated to "... `value` MUST be a string containing a list of comma-separated email addresses."

I think you've already hit all the high points of why we should go this way.
